sudo: required

before_install:
  - sudo apt-get install cmake
  - sudo apt-get install libopenblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install libarpack2-dev
  - sudo apt-get install libarmadillo-dev

language: c++

notifications:
  email:
    on_success: change
    on_failure: change

compiler:
  - clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - make